### PR TITLE
Support more Pythonic use of the RedirectionStorage

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This includes and builds on the commits from PR #14. So you can ignore the first few commits if you want. Or [compare the changes between those two branches](https://github.com/plone/plone.app.redirector/compare/maurits-improve-tests...maurits-more-pythonic).
It fixes issue #13:

- Support using the `in` operator for paths.
- Support using `storage[old_path]` to get the new path, possibly raising KeyError.
- Support using `storage[old_path]` to set or delete new paths.
- Support using `len(storage)` to get the number of paths.

Also: added performance tests.

The performance tests insert 10000 paths by default, which goes really fast:

```
$ time bin/test -s plone.app.redirector -m test_performance
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:
                
  Ran 1 tests with 0 failures, 0 errors, 0 skipped in 0.081 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.

real	0m1.100s
user	0m0.877s
sys	0m0.218s
```

When you are really changing things that might impact performance, you can set environment variable `PLONE_APP_REDIRECTOR_PERFORMANCE_NUMBER` to a higher number. The existence of this variable will also make it more verbose. Sample run with one million paths:

```
$ PLONE_APP_REDIRECTOR_PERFORMANCE_NUMBER=1000000 bin/test -s plone.app.redirector -m test_performance
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:
    1/1 (100.0%)
Running plone.app.redirector storage performance tests.
Inserting 1000000 paths...
Inserting: 8.48 seconds (max 100.0)
Getting length: 0.01 seconds (max 0.1)
Getting iterator: 0.00 seconds (max 0.1)
Listing all: 0.06 seconds (max 1.0)
Listing and getting each single one: 1.65 seconds (max 10.0)
                
  Ran 1 tests with 0 failures, 0 errors, 0 skipped in 10.479 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
```

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Interestingly, these are the performance results for inserting one million paths on Python 2:

```
Running plone.app.redirector storage performance tests.
Inserting 1000000 paths...
Inserting: 11.64 seconds (max 100.0)
Getting length: 0.01 seconds (max 0.1)
Getting iterator: 0.00 seconds (max 0.1)
Listing all: 0.05 seconds (max 1.0)
Listing and getting each single one: 2.42 seconds (max 10.0)
```

So compared with Python 3 above:
- inserting takes 50% longer on Python 2
- listing and getting each single one takes  takes 50% longer on Python 2

This is on Mac.

**Comment by mauritsvanrees** [comment]
Minor thing: I should rename `news/13.bugfix` to `news/13.feature`. But Jenkins is nicely green now, so I don't want to push a change. Can be done after merge.

**Comment by gforcada** [comment]
Just like on the previous review, the `` def test_suite():`` I think is no longer needed. But that can be merged afterwards :+1:

**Pull request merged**
